"""
Django settings for exshare project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import glob

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONF_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'conf')

conf_files = sorted(glob.glob(os.path.join(CONF_DIR, '*.conf')))

for f in conf_files:
    execfile(os.path.abspath(f))